name: 'airbyte_stripe'
version: '0.1.0'
require-dbt-version: ['>=1.0.0']
config-version: 2
profile: 'default'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airbyte_stripe:
    materialized: table
    tmp:
      materialized: view

vars:
  airbyte_stripe:
    customers: "{{ source('airbyte_stripe','customers') }}"
    balance_transactions: "{{ source('airbyte_stripe','balance_transactions') }}" 
    charges_card: "{{ source('airbyte_stripe','charges_card') }}"
    charges: "{{ source('airbyte_stripe','charges') }}"
    payment_intents: "{{ source('airbyte_stripe','payment_intents') }}"
    payouts: "{{ source('airbyte_stripe','payouts') }}"
    refunds: "{{ source('airbyte_stripe','refunds') }}"
