version: 2

sources:
  - name: airbyte_stripe
    schema: "{{ var('stripe_schema', 'stripe') }}"
    database: "{% if target.type != 'spark'%}{{ var('stripe_database', target.database) }}{% endif %}"
    tables:
      - name: customers
      - name: balance_transactions
      - name: charges_card
      - name: charges
      - name: payment_intents
      - name: payouts
      - name: refunds
      - name: invoice_line_items
      - name: invoice_line_items_period
      - name: invoice_line_items_plan
      - name: invoices
      - name: subscriptions
      - name: plans
models:
  - name: stripe__customers
    description: "A table storing all customer info"
    columns:
      - name: id
        description: "The unique identifier for the customer"
        tests:
          - unique
          - not_null
  - name: stripe__balance_transactions
    description: "A table storing all balance transactions and associated charge data"
    columns:
      - name: balance_transaction_id
        description: "The unique identifier for the balance transaction"
        tests:
          - unique
          - not_null
      - name: created_at
        description: "The date the balance transaction was created"
        tests:
          - not_null
      - name: fee
        description: "The fee associated with the balance transaction"
        tests:
          - not_null
      - name: net_balance_change
        description: "The net balance change due to the balance transaction"
        tests:
          - not_null
      - name: type
        description: "The type of balance transaction"
        tests:
          - not_null
      - name: status
        description: "The status of balance transaction"
        tests:
          - not_null
      - name: amount
        description: "The total transaction amount"
        tests:
          - not_null
      - name: currency
        description: "The currency associated with the balance transaction"
        tests:
          - not_null
      - name: exchange_rate
        description: "The exchange rate used for the balance transaction"
      - name: charge_id
        description: "The id of the charge associated with the balance transaction"
        tests:
          - not_null
      - name: charge_created_at
        description: "The date the charge was created"
      - name: card_brand
        description: "The card brand associated with the charge"
      - name: card_funding
        description: "The card funding type associated with the charge"
      - name: card_country
        description: "The country of the card charged"
      - name: charge_amount
        description: "The total charge amount"
      - name: charge_currency
        description: "The currency associated with the charge"
      - name: customer_description
        description: "The customer description associated with balance transaction"
      - name: payout_id
        description: "The id of the payout associated with the balance transaction"
      - name: payout_arrival_date
        description: "The date the payout is due to arrive"
      - name: payout_status
        description: "The status of payout"
      - name: payout_type
        description: "The type of payout"
      - name: payout_description
        description: "The user specified source of the payout" 
      - name: refund_reason
        description: "The refund reason (if applicable)"
  - name: stripe__invoice_line_items
    description: "A table storing all line items associated with an invoice"
    columns:
      - name: invoice_id
        description: "The unique identifier for the balance transaction"
        tests:
          - unique
          - not_null
      - name: invoice_number
        description: "The invoice number"
        tests:
          - not_null
      - name: invoice_created_at
        description: "The date the invoice was created"
        tests:
          - not_null
      - name: status
        description: "The status of the invoice"
        tests:
          - not_null
      - name: due_date
        description: "The due date of the invoice"
        tests:
          - not_null
      - name: amount_due
        description: "The total amount due for the invoice"
        tests:
          - not_null
      - name: subtotal
        description: "The subtotal amount for the invoice"
        tests:
          - not_null
      - name: tax
        description: "The tax amount for the invoice"
        tests:
          - not_null
      - name: total
        description: "The total amount for the invoice"
        tests:
          - not_null
      - name: amount_paid
        description: "The total amount paid for the invoice"
      - name: amount_remaining
        description: "The amount remaining to be paid for the invoice"
      - name: attempt_count
        description: "The number of attempts sent for this invoice"
      - name: description
        description: "The description of the invoice"
      - name: invoice_line_item_id
        description: "The unique id of the invoice line item"
        tests:
          - not_null
          - unique
      - name: line_item_description
        description: "The description of the line item"
      - name: line_item_amount
        description: "The price of line item"
      - name: line_item_quantity
        description: "The total quantity of the line item"
      - name: period_start
        description: "The datetime of the period start for the invoice"
      - name: period_end
        description: "The datetime of the period end for the invoice"
      - name: balance_transaction_id
        description: "The unique id of the associated balance transaction"
        tests:
          - not_null
      - name: charge_amount
        description: "The amount charged for the line item"
      - name: charge_status
        description: "The status of the charge for the line item"
      - name: charge_created_at
        description: "The datetime when the charge for the line item was created"
      - name: customer_description
        description: "The description of the customer associated with line item purchase"
      - name: customer_email
        description: "The email of the customer associated with line item purchase"
      - name: customer_id
        description: "The unique id of the customer associated with line item purchase"
      - name: subscription_id
        description: "The unique id of the subscription purchase (if applicable)"
      - name: subscription_billing
        description: "The billing used for the subscription purchase"
      - name: subscription_start_date
        description: "The start date of the subscription purchase"
      - name: subscription_end_date
        description: "The end date of the subscription purchase"
      - name: plan_id
        description: "The plan associated with the purchased subscription"
      - name: plan_is_active
        description: "A flag for whether the subscription plan is active"
      - name: plan_amount
        description: "The total amount for the subscription plan"
      - name: plan_interval
        description: "The interval the subscription plan is charged at"
      - name: plan_interval_count
        description: "The number of intervals the subscription plan is charged"
      - name: plan_nickname
        description: "The nickname of the subscription plan"
      - name: plan_product_id
        description: "The unique id of the product associated with subscription plan"
