version: 2

sources:
  - name: airbyte_stripe
    schema: "{{ var('stripe_schema', 'stripe') }}"
    database: "{% if target.type != 'spark'%}{{ var('stripe_database', target.database) }}{% endif %}"
    tables:
      - name: customers
      - name: customers_address
      - name: balance_transactions
      - name: charges_card
      - name: charges
      - name: payment_intents
      - name: payouts
      - name: refunds
      - name: invoice_line_items
      - name: invoice_line_items_period
      - name: invoice_line_items_plan
      - name: invoices
      - name: subscriptions
      - name: plans
models:
  - name: stripe__customers
    description: "A table storing all customer info"
    columns:
      - name: customer_id
        description: "The unique identifier of the customer"
        tests:
          - unique
          - not_null
      - name: customer_description
        description: "The unique identifier for the customer"
        tests:
          - not_null
      - name: customer_created_at
        description: "The date the customer was created"
        tests:
          - not_null
      - name: total_sales
        description: "The total amount of sales for the customer"
        tests:
          - not_null
      - name: total_refunds
        description: "The total amount of refunds to the customer"
        tests:
          - not_null
      - name: total_gross_transaction_amount
        description: "The total gross transaction amount for the customer"
        tests:
          - not_null
      - name: total_fees
        description: "The total amount fees generated by the customer"
        tests:
          - not_null
      - name: total_net_transaction_amount
        description: "The total net transaction amount for the customer"
        tests:
          - not_null
      - name: total_failed_charge_amount
        description: "The total amount of failed charges to the customer"
        tests:
          - not_null
      - name: total_failed_charge_count
        description: "The total number of failed charges to this customer"
        tests:
          - not_null
      - name: total_sales_count
        description: "The total number of sales made to the customer"
        tests:
          - not_null
      - name: total_refund_count
        description: "The total number of refunds made to the customer"
        tests:
          - not_null
      - name: sales_this_month
        description: "The total amount of sales made this month"
        tests:
          - not_null
      - name: refunds_this_month
        description: "The total amount of refunds made this month"
        tests:
          - not_null
      - name: gross_transaction_amount_this_month
        description: "The total gross transaction amount this month"
        tests:
          - not_null
      - name: net_transaction_amount_this_month
        description: "The total net transaction amount this month"
        tests:
          - not_null
      - name: sales_count_this_month
        description: "The total number of sales made this month"
        tests:
          - not_null
      - name: refund_count_this_month
        description: "The total number of refund_count made this month"
        tests:
          - not_null
      - name: failed_charge_count_this_month
        description: "The total number of failed_charge_count made this month"
        tests:
          - not_null
      - name: failed_charge_amount_this_month
        description: "The total number of failed_charge_amount made this month"
        tests:
          - not_null
      - name: customer_currency
        description: "The currency set for this currency"
      - name: default_card_id
        description: "The unique identifier of the default customer card"
      - name: shipping_name
        description: "The name of the shipping service"
      - name: shipping_address_line_1
        description: "The 1st line of the customer shipping address"
      - name: shipping_address_line_2
        description: "The 2nd line of the customer shipping address"
      - name: shipping_address_city
        description: "The city of the customer shipping address"
      - name: shipping_address_state
        description: "The state of the customer shipping address"
      - name: shipping_address_country
        description: "The country of the customer shipping address"
      - name: shipping_address_postal_code
        description: "The postal code of the customer shipping address"
      - name: phone_number
        description: "The phone number of the customer"
  - name: stripe__balance_transactions
    description: "A table storing all balance transactions and associated charge data"
    columns:
      - name: balance_transaction_id
        description: "The unique identifier for the balance transaction"
        tests:
          - unique
          - not_null
      - name: created_at
        description: "The date the balance transaction was created"
        tests:
          - not_null
      - name: fee
        description: "The fee associated with the balance transaction"
        tests:
          - not_null
      - name: net_balance_change
        description: "The net balance change due to the balance transaction"
        tests:
          - not_null
      - name: type
        description: "The type of balance transaction"
        tests:
          - not_null
      - name: status
        description: "The status of balance transaction"
        tests:
          - not_null
      - name: amount
        description: "The total transaction amount"
        tests:
          - not_null
      - name: currency
        description: "The currency associated with the balance transaction"
        tests:
          - not_null
      - name: exchange_rate
        description: "The exchange rate used for the balance transaction"
      - name: charge_id
        description: "The id of the charge associated with the balance transaction"
        tests:
          - not_null
      - name: charge_created_at
        description: "The date the charge was created"
      - name: card_brand
        description: "The card brand associated with the charge"
      - name: card_funding
        description: "The card funding type associated with the charge"
      - name: card_country
        description: "The country of the card charged"
      - name: charge_amount
        description: "The total charge amount"
      - name: charge_currency
        description: "The currency associated with the charge"
      - name: customer_description
        description: "The customer description associated with balance transaction"
      - name: payout_id
        description: "The id of the payout associated with the balance transaction"
      - name: payout_arrival_date
        description: "The date the payout is due to arrive"
      - name: payout_status
        description: "The status of payout"
      - name: payout_type
        description: "The type of payout"
      - name: payout_description
        description: "The user specified source of the payout" 
      - name: refund_reason
        description: "The refund reason (if applicable)"
  - name: stripe__invoice_line_items
    description: "A table storing all line items associated with an invoice"
    columns:
      - name: invoice_id
        description: "The unique identifier for the balance transaction"
        tests:
          - unique
          - not_null
      - name: invoice_number
        description: "The invoice number"
        tests:
          - not_null
      - name: invoice_created_at
        description: "The date the invoice was created"
        tests:
          - not_null
      - name: status
        description: "The status of the invoice"
        tests:
          - not_null
      - name: due_date
        description: "The due date of the invoice"
        tests:
          - not_null
      - name: amount_due
        description: "The total amount due for the invoice"
        tests:
          - not_null
      - name: subtotal
        description: "The subtotal amount for the invoice"
        tests:
          - not_null
      - name: tax
        description: "The tax amount for the invoice"
        tests:
          - not_null
      - name: total
        description: "The total amount for the invoice"
        tests:
          - not_null
      - name: amount_paid
        description: "The total amount paid for the invoice"
      - name: amount_remaining
        description: "The amount remaining to be paid for the invoice"
      - name: attempt_count
        description: "The number of attempts sent for this invoice"
      - name: description
        description: "The description of the invoice"
      - name: invoice_line_item_id
        description: "The unique id of the invoice line item"
        tests:
          - not_null
          - unique
      - name: line_item_description
        description: "The description of the line item"
      - name: line_item_amount
        description: "The price of line item"
      - name: line_item_quantity
        description: "The total quantity of the line item"
      - name: period_start
        description: "The datetime of the period start for the invoice"
      - name: period_end
        description: "The datetime of the period end for the invoice"
      - name: balance_transaction_id
        description: "The unique id of the associated balance transaction"
        tests:
          - not_null
      - name: charge_amount
        description: "The amount charged for the line item"
      - name: charge_status
        description: "The status of the charge for the line item"
      - name: charge_created_at
        description: "The datetime when the charge for the line item was created"
      - name: customer_description
        description: "The description of the customer associated with line item purchase"
      - name: customer_email
        description: "The email of the customer associated with line item purchase"
      - name: customer_id
        description: "The unique id of the customer associated with line item purchase"
      - name: subscription_id
        description: "The unique id of the subscription purchase (if applicable)"
      - name: subscription_billing
        description: "The billing used for the subscription purchase"
      - name: subscription_start_date
        description: "The start date of the subscription purchase"
      - name: subscription_end_date
        description: "The end date of the subscription purchase"
      - name: plan_id
        description: "The plan associated with the purchased subscription"
      - name: is_plan_active
        description: "A flag for whether the subscription plan is active"
      - name: plan_amount
        description: "The total amount for the subscription plan"
      - name: plan_interval
        description: "The interval the subscription plan is charged at"
      - name: plan_interval_count
        description: "The number of intervals the subscription plan is charged"
      - name: plan_nickname
        description: "The nickname of the subscription plan"
      - name: plan_product_id
        description: "The unique id of the product associated with subscription plan"
  - name: stripe__subscriptions
    description: "A table storing the details of all subscription plans used by customers"
    columns:
      - name: subscription_id
        description: "The unique identifier for the subscription"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "The unique identifier for the customer"
        tests:
          - not_null
      - name: customer_description
        description: "The description of the customer"
        tests:
          - not_null
      - name: customer_email
        description: "The email of the customer"
        tests:
          - not_null
      - name: status
        description: "The status of the subscription"
        tests:
          - not_null
      - name: start_date
        description: "The start date of the subscription"
        tests:
          - not_null
      - name: end_date
        description: "The end date of the subscription"
        tests:
          - not_null
      - name: subscription_billing
        description: "The type of billing used for the subscription"
        tests:
          - not_null
      - name: billing_cycle_anchor
        description: "The billing cycle anchor for the subscription"
        tests:
          - not_null
      - name: canceled_at
        description: "The datetime the invoice was canceled"
      - name: created_at
        description: "The datetime the invoice was created"
        tests:
          - not_null
      - name: current_period_start
        description: "The datetime the current subscription period starts"
        tests:
          - not_null
      - name: current_period_end
        description: "The datetime the current subscription period ends"
        tests:
          - not_null
      - name: trial_start
        description: "The datetime the trial starts"
      - name: trial_end
        description: "The datetime the trial ends"
      - name: days_until_due
        description: "The number of days until the subscription id canceled"
      - name: is_cancel_at_period_end
        description: "A flag for whether the subscription will be cancled at the end of the period"
      - name: number_invoices_generated
        description: "The number of invoice generated for this subscription"
        tests:
          - not_null
      - name: total_amount_billed
        description: "The total amount billed for the subscription"
        tests:
          - not_null
      - name: total_amount_paid
        description: "The total amount paid for the subscription"
        tests:
          - not_null
      - name: total_amount_remaining
        description: "The total amount remaining for the subscription"
        tests:
          - not_null
      - name: most_recent_invoice_at
        description: "The datetime the most recent invoice was generated"
      - name: average_invoice_amount
        description: "The average amount charged for the subscription"
        tests:
          - not_null
      - name: average_line_item_amount
        description: "The average amount of a line item which is bought as part of the subscription"
        tests:
          - not_null
      - name: average_num_invoice_items
        description: "The average amount of line items charged for a subscription"
        tests:
          - not_null
  - name: "stripe__daily_overview"
    description: "A table storing the daily overview statistics of your stripe account"
    columns:
      - name: date
        description: "The date for the Stripe record"
        tests:
          - unique
          - not_null
      - name: total_sales
        description: "The total amount of sales done on the date"
        tests:
          - not_null
      - name: total_refunds
        description: "The total amount of refunds done on the date"
        tests:
          - not_null
      - name: total_adjustments
        description: "The total amount of adjustments done on the date"
        tests:
          - not_null
      - name: total_other_transactions
        description: "The total amount of other transactions done on the date"
        tests:
          - not_null
      - name: total_gross_transaction_amount
        description: "The total amount of gross_transaction_amount done on the date"
        tests:
          - not_null
      - name: total_payout_fees
        description: "The total amount of payout_fees done on the date"
        tests:
          - not_null
      - name: total_gross_payment_amount
        description: "The total amount of gross_payment_amount done on the date"
        tests:
          - not_null
      - name: total_failed_charge_amount
        description: "The total amount of failed charges on the date"
        tests:
          - not_null
      - name: total_sales_count
        description: "The total number of sales done on the date"
        tests:
          - not_null
      - name: total_payouts_count
        description: "The total number of payouts done on the date"
        tests:
          - not_null
      - name: total_adjustments_count
        description: "The total number of adjustments done on the date"
        tests:
          - not_null
      - name: total_failed_charge_count
        description: "The total number of failed charges on the date"
        tests:
          - not_null
      - name: daily_end_balance
        description: "The daily end balance on the date"
        tests:
          - not_null
      - name: churned_subscriptions
        description: "The number of subscriptions that have been churned on the date"
      - name: new_subscriptions
        description: "The number of new subscriptions on the date"
      - name: active_subscriptions
        description: "The snapshot of the total number of subscriptions that were active at the date"
      - name: churned_mrr
        description: "The amount of monthly recurring revenue churned on that date"
      - name: new_mrr
        description: "The amount of new monthly recurring revenue gained on the date"
      - name: mrr
        description: "The snapshot of the total monthly recurring revenue on the date"
      - name: mrr_per_subscription
        description: "The monthly recurring revenue per active subscription"
      - name: mrr_per_customer
        description: "The monthly recurring revenue per active customer"
      - name: customers_diff
        description: "The change in number of customers from the previous date to the current date"
      - name: subscriptions_diff
        description: "The change in number of subscriptions from the previous date to the current date"
      - name: mrr_diff
        description: "The change in the number of customers from the previous date to the current date"
      
